// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVKzRj5w22Vjnhb3aIAvzWU04pI1EDugc',
    appId: '1:973249498094:web:67a5023d706fd17a591cff',
    messagingSenderId: '973249498094',
    projectId: 'tree-shop-v3-prm',
    authDomain: 'tree-shop-v3-prm.firebaseapp.com',
    storageBucket: 'tree-shop-v3-prm.firebasestorage.app',
    measurementId: 'G-HZ5NDXLTX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-0mp5BRdG2qPZPasLG6LVTKn8SRnk9Do',
    appId: '1:973249498094:android:3037938090f99838591cff',
    messagingSenderId: '973249498094',
    projectId: 'tree-shop-v3-prm',
    storageBucket: 'tree-shop-v3-prm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS3sEa3dimAoKlmbwS0IJdBISJv3ffCsY',
    appId: '1:973249498094:ios:fcffc6cd22457a2c591cff',
    messagingSenderId: '973249498094',
    projectId: 'tree-shop-v3-prm',
    storageBucket: 'tree-shop-v3-prm.firebasestorage.app',
    iosBundleId: 'com.treeshop.plantShopApp',
  );

}